"""empty message

Revision ID: 3d41930d2bdc
Revises: 971c0579fb84
Create Date: 2020-05-02 11:49:24.660132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d41930d2bdc'
down_revision = '971c0579fb84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_genres',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
    )
    op.create_table('venue_genres',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
    )
    op.alter_column('Artist', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Artist', 'genres')
    op.alter_column('City', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('City', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Genre', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Venue', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Genre', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('City', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('City', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.alter_column('Artist', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('venue_genres')
    op.drop_table('artist_genres')
    # ### end Alembic commands ###
