"""empty message

Revision ID: c4f9309877c0
Revises: 83f3bba3e2bc
Create Date: 2020-05-09 12:02:20.878354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f9309877c0'
down_revision = '83f3bba3e2bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('regitration_time', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('regitration_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'regitration_time')
    op.drop_column('Artist', 'regitration_time')
    # ### end Alembic commands ###
